{% set version = "0.2.0" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-metatools
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/metatools_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/metatools/metatools_{{ version }}.tar.gz
  sha256: 8042b6df4a329a6437e0b7a02f1b1a944949e8341761524c16b45e2547be7ebf

build:
  number: 1
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'        # [win]
    - '*/Rblas.dll'    # [win]
    - '*/Rlapack.dll'  # [win]

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-cli
    - r-dplyr
    - r-lifecycle
    - r-magrittr
    - r-metacore >=0.2.0
    - r-purrr
    - r-rlang
    - r-stringr
    - r-tibble
    - r-tidyr
  run:
    - r-base
    - r-cli
    - r-dplyr
    - r-lifecycle
    - r-magrittr
    - r-metacore >=0.2.0
    - r-purrr
    - r-rlang
    - r-stringr
    - r-tibble
    - r-tidyr

test:
  commands:
    - $R -e "library('metatools')"           # [not win]
    - "\"%R%\" -e \"library('metatools')\""  # [win]

about:
  home: https://github.com/pharmaverse/metatools, https://pharmaverse.github.io/metatools/
  license: MIT
  summary: Uses the metadata information stored in 'metacore' objects to check and build metadata associated columns.
  license_family: MIT
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/MIT'
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
